
print("\n**Paso 1: Preparación y Organización**")
print("Antes de empezar, asegúrate de tener todo lo necesario:")
print("- Un fregadero limpio o un recipiente grande con agua.")
print("- Agua caliente y fría.")
print("- Jabón lavavajillas de buena calidad.")
print("- Una esponja adecuada (ver detalles más adelante).")
print("- Un cepillo para platos (opcional, para suciedad difícil).")
print("- Un paño de cocina limpio y seco para secar.")
print("- Un escurreplatos (opcional, pero muy útil).")
print("- Un recipiente para desechar restos de comida.")

print("\n**Paso 2: Retirar los Restos de Comida**")
print("Es crucial eliminar todos los restos grandes de comida de los platos.")
print("Utiliza una espátula, un tenedor o simplemente tus manos (con guantes si lo prefieres)")
print("para raspar los residuos y depositarlos en el recipiente destinado a ello.")
print("Esto evitará que la suciedad obstruya el fregadero y facilitará el lavado.")

print("\n**Paso 3: Llenar el Fregadero (o Recipiente)**")
print("Si tienes un fregadero doble, llena uno de los lados con agua caliente y añade el jabón lavavajillas.")
print("La cantidad de jabón dependerá de la cantidad de platos y del nivel de suciedad.")
print("Generalmente, unas cuantas gotas son suficientes. El agua debe sentirse jabonosa pero no excesivamente.")
print("Si solo tienes un fregadero o un recipiente, llénalo de manera similar.")

print("\n**Paso 4: Selección de la Esponja Adecuada**")
print("La elección de la esponja es importante para una limpieza eficaz sin dañar tus platos:")
print("- **Esponja de celulosa (la común):** Ideal para la mayoría de los platos y utensilios. Suave y absorbente.")
print("- **Esponja con fibra abrasiva (un lado más áspero):** Útil para remover suciedad pegada, pero úsala con cuidado en superficies delicadas (como teflón o cristal) para evitar rayones.")
print("- **Cepillo para platos:** Excelente para ollas, sartenes y suciedad difícil. Permite aplicar presión sin mojarte tanto las manos.")
print("- **Estropajo de acero (lana de acero):** Solo para suciedad muy incrustada en ollas y sartenes resistentes. ¡Nunca lo uses en platos, cristalería o superficies antiadherentes!")
print("- **Esponjas de silicona:** Higiénicas y duraderas, pero pueden no ser tan efectivas para suciedad muy adherida.")

print("\n**Paso 5: Orden de Lavado - De lo Menos a lo Más Sucio**")
print("Lavar los platos en un orden específico ayuda a mantener el agua jabonosa limpia por más tiempo:")
print("1. **Vasos y copas:** Suelen ser los menos sucios.")
print("2. **Tazas y platillos:** Después de los vasos.")
print("3. **Cubiertos:** Tenedores, cuchillos y cucharas.")
print("   - Ten cuidado al lavar cuchillos, sujétalos con firmeza por el mango y lávalos con la hoja apuntando lejos de ti.")
print("4. **Platos:** Empezando por los más pequeños y terminando por los más grandes y sucios.")
print("5. **Bowls y ensaladeras:**")
print("6. **Utensilios de cocina:** Espátulas, cucharones, etc.")
print("7. **Ollas y sartenes:** Suelen ser los más difíciles. Si tienen comida muy pegada, déjalas remojando en agua caliente con jabón por un tiempo antes de lavarlas.")

print("Paso 6: El Proceso de Lavado")
print("1. Sumerge el objeto en el agua jabonosa.")
print("2. Utiliza la esponja o el cepillo para frotar suavemente todas las superficies, tanto por dentro como por fuera.")
print("   - Presta especial atención a los bordes, las asas y las áreas donde la suciedad tiende a acumularse.")
print("   - Para suciedad pegada, puedes dejar el objeto remojando un poco más o usar el lado abrasivo de la esponja con cuidado.")
print("3. Asegúrate de eliminar toda la grasa y los residuos de comida.")

print("Paso 7: Enjuague")
print("Una vez que el objeto esté limpio, enjuágalo bien con agua corriente limpia y fría o caliente.")
print("Asegúrate de eliminar todo el jabón, ya que los residuos pueden dejar manchas o un sabor desagradable.")
print("Si tienes un fregadero doble, puedes usar el segundo lado lleno de agua limpia para enjuagar.")

print("Paso 8: Secado")
print("Secar los platos correctamente es importante para evitar manchas de agua y asegurar su higiene:")
print("- **Secado al aire:** Coloca los platos limpios en un escurreplatos y deja que se sequen al aire. Esto es conveniente para grandes cantidades.")
print("- **Secado con paño:** Utiliza un paño de cocina limpio y seco para secar cada pieza individualmente. Asegúrate de que el paño esté limpio para evitar transferir gérmenes o pelusas.")
print("  - Empieza por los vasos y la cristalería para evitar que se empañen.")
print("  - Luego seca los platos, los cubiertos y otros utensilios.")

print("Paso 9: Limpieza Final")
print("Una vez que todos los platos estén limpios y secos, asegúrate de:")
print("- Enjuagar el fregadero para eliminar cualquier resto de jabón o suciedad.")
print("- Limpiar la esponja y dejarla secar en un lugar ventilado.")
print("- Cambiar el agua del fregadero si fue necesario durante el lavado.")
print("- Limpiar el paño de cocina regularmente.")
